import Loading from '@/components/custom/Loading'
import Whatsapp from '@/components/custom/Whatsapp'
import Intro from '@/containers/resellers/Intro'
import Planes from '@/containers/resellers/Planes'
import Footer from '@/layouts/footers/Footer'
import Nav from '@/layouts/navs/Nav'
import Head from 'next/head'
import Script from 'next/script'
import { useEffect, useState } from 'react'

export default function Home() {
    const [load, setLoad] = useState(true)
    useEffect(() => {
        setLoad(false)
    }, [])
    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <Nav />

            <main className='dg-theme'>
                <Intro />
                <Planes />
            </main>

            <Footer />

            <Whatsapp indicativo={58} number={4126679598} />
            {load && <Loading />}
            <Script strategy='afterInteractive' src="/lib/waypoints/waypoints.min.js" />
            <Script strategy='afterInteractive' src="/lib/wow/wow.min.js" />
            <Script strategy='afterInteractive' src="/lib/wow/wow.min.js" />
            <Script strategy='afterInteractive' src="/lib/owlcarousel/owl.carousel.min.js" />
            <Script strategy='lazyOnload' src="/lib/mobile-nav/mobile-nav.js" />
            <Script strategy='lazyOnload' src="/lib/easing/easing.min.js" />
            <Script strategy='lazyOnload' src="/js/main.js" />
        </>
    )
}
